services:
  postgres: # host is coming from here
    image: postgres:15
    container_name: plated-postgres
    ports: 
      - "5435:5432" # from this localhost 5435 (outside) docker connects to pgadmin, 5432 is inside docker (only can access through postgres host)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: plated-server
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env